apiVersion: v1
name: vsphere-cpi-csi
version: 1.0.2-rancheros
appVersion: 1.0.2-rancheros
description: vSphere CPI manager v1.1.0 and CSI drivers v1.0.2
keywords:
  - vsphere
  - vmware
  - esxi
  - cpi
  - csi
  - storage
maintainers:
  - name: Stefan van Gastel
    email: stefanvangastel@gmail.com
engine: gotpl
